services:

  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports: [ "11434:11434" ]
    volumes:
      - ./storage/ollama_data:/root/.ollama
    pull_policy: always
    tty: true
    restart: unless-stopped
