services:
  cloudbeaver:
    image: dbeaver/cloudbeaver:latest
    container_name: rag-cloudbeaver
    restart: unless-stopped
    ports:
      - "8978:8978"
    volumes:
      - ./storage/cloudbeaver:/opt/cloudbeaver/workspace
    networks:
      - rag-network

networks:
  rag-network:
    external: true
