include:
  - docker-compose.postgres.yml
  - docker-compose.zitadel.yml
  - docker-compose.whisper.yml
  - docker-compose.piper.yml
  - docker-compose.prometheus.yml
  - docker-compose.grafana.yml
  - docker-compose.cloudbeaver.yml
