services:
  cloudbeaver:
    image: dbeaver/cloudbeaver:latest
    container_name: macular-cloudbeaver
    restart: unless-stopped
    ports:
      - "8978:8978"
    volumes:
      - ./storage/cloudbeaver:/opt/cloudbeaver/workspace
    networks:
      - macular-network

networks:
  macular-network:
    external: true
