apiVersion: 1

datasources:
  - name: PostgreSQL
    type: postgres
    access: proxy
    url: postgres:5432
    database: macular_society
    user: macular
    secureJsonData:
      password: macular_dev
    jsonData:
      sslmode: "disable"
      maxOpenConns: 10
      maxIdleConns: 10
      connMaxLifetime: 14400
    editable: true
